# Generated by Django 4.1.9 on 2023-06-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycletracking',
            old_name='last_day_menstraution',
            new_name='last_day_menstruation',
        ),
    ]
