# Generated by Django 4.1.9 on 2023-06-05 09:33

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_last_day_menstruation_cycletracking_last_menstruation_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletracking',
            name='menstrual_events',
            field=recurrence.fields.RecurrenceField(default=''),
        ),
    ]
