# Generated by Django 4.1.9 on 2023-06-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_profile_picture_goalsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalsetting',
            name='user',
        ),
    ]
